(function(c){c.fmatter={};c.extend(c.fmatter,{isBoolean:function(a){return typeof a==="boolean"},isObject:function(a){return a&&(typeof a==="object"||c.isFunction(a))||false},isString:function(a){return typeof a==="string"},isNumber:function(a){return typeof a==="number"&&isFinite(a)},isNull:function(a){return a===null},isUndefined:function(a){return typeof a==="undefined"},isValue:function(a){return this.isObject(a)||this.isString(a)||this.isNumber(a)||this.isBoolean(a)},isEmpty:function(a){if(!this.isString(a)&&
this.isValue(a))return false;else if(!this.isValue(a))return true;a=c.trim(a).replace(/\&nbsp\;/ig,"").replace(/\&#160\;/ig,"");return a===""}});c.fn.fmatter=function(a,b,d,f,e){var i=b;d=c.extend({},c.jgrid.formatter,d);if(c.fn.fmatter[a])i=c.fn.fmatter[a](b,d,f,e);return i};c.fmatter.util={NumberFormat:function(a,b){c.fmatter.isNumber(a)||(a*=1);if(c.fmatter.isNumber(a)){var d=a<0,f=a+"",e=b.decimalSeparator?b.decimalSeparator:".";if(c.fmatter.isNumber(b.decimalPlaces)){var i=b.decimalPlaces;f=
Math.pow(10,i);f=Math.round(a*f)/f+"";a=f.lastIndexOf(".");if(i>0){if(a<0){f+=e;a=f.length-1}else if(e!==".")f=f.replace(".",e);for(;f.length-1-a<i;)f+="0"}}if(b.thousandsSeparator){i=b.thousandsSeparator;a=f.lastIndexOf(e);a=a>-1?a:f.length;e=f.substring(a);for(var g=-1,h=a;h>0;h--){g++;if(g%3===0&&h!==a&&(!d||h>1))e=i+e;e=f.charAt(h-1)+e}f=e}f=b.prefix?b.prefix+f:f;return f=b.suffix?f+b.suffix:f}else return a},DateFormat:function(a,b,d,f){var e=b.match(/^\/Date((([-+])?[0-9]+)(([-+])([0-9]{2})([0-9]{2}))?)\/$/),
i=function(m,r){m=String(m);for(r=parseInt(r,10)||2;m.length<r;)m="0"+m;return m},g={m:1,d:1,y:1970,h:0,i:0,s:0,u:0},h=0,j,k=["i18n"];k.i18n={dayNames:f.dayNames,monthNames:f.monthNames};if(a in f.masks)a=f.masks[a];if(b.constructor===Number)h=new Date(b);else if(b.constructor===Date)h=b;else if(e!==null){h=new Date(parseInt(e[1],10));if(e[3]){g=Number(e[5])*60+Number(e[6]);g*=e[4]=="-"?1:-1;g-=h.getTimezoneOffset();h.setTime(Number(Number(h)+g*60*1E3))}}else{b=b.split(/[\\\/:_;.,\t\T\s-]/);a=a.split(/[\\\/:_;.,\t\T\s-]/);
e=0;for(j=a.length;e<j;e++){if(a[e]=="M"){h=c.inArray(b[e],k.i18n.monthNames);if(h!==-1&&h<12)b[e]=h+1}if(a[e]=="F"){h=c.inArray(b[e],k.i18n.monthNames);if(h!==-1&&h>11)b[e]=h+1-12}if(b[e])g[a[e].toLowerCase()]=parseInt(b[e],10)}if(g.f)g.m=g.f;if(g.m===0&&g.y===0&&g.d===0)return"&#160;";g.m=parseInt(g.m,10)-1;h=g.y;if(h>=70&&h<=99)g.y=1900+g.y;else if(h>=0&&h<=69)g.y=2E3+g.y;h=new Date(g.y,g.m,g.d,g.h,g.i,g.s,g.u)}if(d in f.masks)d=f.masks[d];else d||(d="Y-m-d");g=h.getHours();a=h.getMinutes();b=
h.getDate();e=h.getMonth()+1;j=h.getTimezoneOffset();var l=h.getSeconds(),o=h.getMilliseconds(),n=h.getDay(),p=h.getFullYear(),q=(n+6)%7+1,s=(new Date(p,e-1,b)-new Date(p,0,1))/864E5,t={d:i(b),D:k.i18n.dayNames[n],j:b,l:k.i18n.dayNames[n+7],N:q,S:f.S(b),w:n,z:s,W:q<5?Math.floor((s+q-1)/7)+1:Math.floor((s+q-1)/7)||(((new Date(p-1,0,1)).getDay()+6)%7<4?53:52),F:k.i18n.monthNames[e-1+12],m:i(e),M:k.i18n.monthNames[e-1],n:e,t:"?",L:"?",o:"?",Y:p,y:String(p).substring(2),a:g<12?f.AmPm[0]:f.AmPm[1],A:g<
12?f.AmPm[2]:f.AmPm[3],B:"?",g:g%12||12,G:g,h:i(g%12||12),H:i(g),i:i(a),s:i(l),u:o,e:"?",I:"?",O:(j>0?"-":"+")+i(Math.floor(Math.abs(j)/60)*100+Math.abs(j)%60,4),P:"?",T:(String(h).match(/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g)||[""]).pop().replace(/[^-+\dA-Z]/g,""),Z:"?",c:"?",r:"?",U:Math.floor(h/1E3)};return d.replace(/\\.|[dDjlNSwzWFmMntLoYyaABgGhHisueIOPTZcrU]/g,function(m){return m in t?t[m]:m.substring(1)})}};
c.fn.fmatter.defaultFormat=function(a,b){return c.fmatter.isValue(a)&&a!==""?a:b.defaultValue?b.defaultValue:"&#160;"};c.fn.fmatter.email=function(a,b){return c.fmatter.isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):'<a href="mailto:'+a+'">'+a+"</a>"};c.fn.fmatter.checkbox=function(a,b){var d=c.extend({},b.checkbox);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));b=d.disabled===true?'disabled="disabled"':"";if(c.fmatter.isEmpty(a)||c.fmatter.isUndefined(a))a=
c.fn.fmatter.defaultFormat(a,d);a+="";a=a.toLowerCase();return'<input type="checkbox" '+(a.search(/(false|0|no|off)/i)<0?" checked='checked' ":"")+' value="'+a+'" offval="no" '+b+"/>"};c.fn.fmatter.link=function(a,b){var d={target:b.target},f="";c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(d.target)f="target="+d.target;return c.fmatter.isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):"<a "+f+' href="'+a+'">'+a+"</a>"};c.fn.fmatter.showlink=function(a,b){var d=
{baseLinkUrl:b.baseLinkUrl,showAction:b.showAction,addParam:b.addParam||"",target:b.target,idName:b.idName},f="";c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(d.target)f="target="+d.target;d=d.baseLinkUrl+d.showAction+"?"+d.idName+"="+b.rowId+d.addParam;return c.fmatter.isString(a)||c.fmatter.isNumber(a)?"<a "+f+' href="'+d+'">'+a+"</a>":c.fn.fmatter.defaultFormat(a,b)};c.fn.fmatter.integer=function(a,b){var d=c.extend({},b.integer);c.fmatter.isUndefined(b.colModel.formatoptions)||
(d=c.extend({},d,b.colModel.formatoptions));if(c.fmatter.isEmpty(a))return d.defaultValue;return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.number=function(a,b){var d=c.extend({},b.number);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(c.fmatter.isEmpty(a))return d.defaultValue;return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.currency=function(a,b){var d=c.extend({},b.currency);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},
d,b.colModel.formatoptions));if(c.fmatter.isEmpty(a))return d.defaultValue;return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.date=function(a,b,d,f){d=c.extend({},b.date);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));return!d.reformatAfterEdit&&f=="edit"?c.fn.fmatter.defaultFormat(a,b):c.fmatter.isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):c.fmatter.util.DateFormat(d.srcformat,a,d.newformat,d)};c.fn.fmatter.select=function(a,b){a+="";var d=false,f=[];
if(c.fmatter.isUndefined(b.colModel.formatoptions)){if(!c.fmatter.isUndefined(b.colModel.editoptions))d=b.colModel.editoptions.value}else d=b.colModel.formatoptions.value;if(d){var e=b.colModel.editoptions.multiple===true?true:false,i=[],g;if(e){i=a.split(",");i=c.map(i,function(l){return c.trim(l)})}if(c.fmatter.isString(d))for(var h=d.split(";"),j=0,k=0;k<h.length;k++){g=h[k].split(":");if(g.length>2)g[1]=jQuery.map(g,function(l,o){if(o>0)return l}).join(":");if(e){if(jQuery.inArray(g[0],i)>-1){f[j]=
g[1];j++}}else if(c.trim(g[0])==c.trim(a)){f[0]=g[1];break}}else if(c.fmatter.isObject(d))if(e)f=jQuery.map(i,function(l){return d[l]});else f[0]=d[a]||""}a=f.join(", ");return a===""?c.fn.fmatter.defaultFormat(a,b):a};c.fn.fmatter.rowactions=function(a,b,d,f){var e={keys:false,editbutton:true,delbutton:true,onEdit:null,onSuccess:null,afterSave:null,onError:null,afterRestore:null,extraparam:{oper:"edit"},url:null,delOptions:{}};f=c("#"+b)[0].p.colModel[f];c.fmatter.isUndefined(f.formatoptions)||(e=
c.extend(e,f.formatoptions));f=function(g){e.afterSave&&e.afterSave(g);c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del","#"+b).show();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b).hide()};var i=function(g){e.afterRestore&&e.afterRestore(g);c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del","#"+b).show();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b).hide()};switch(d){case "edit":c("#"+b).jqGrid("editRow",a,e.keys,e.onEdit,e.onSuccess,
e.url,e.extraparam,f,e.onError,i);c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del","#"+b).hide();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b).show();break;case "save":c("#"+b).jqGrid("saveRow",a,e.onSuccess,e.url,e.extraparam,f,e.onError,i);c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del","#"+b).show();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b).hide();break;case "cancel":c("#"+b).jqGrid("restoreRow",a,i);c("tr#"+a+" div.ui-inline-edit, tr#"+
a+" div.ui-inline-del","#"+b).show();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b).hide();break;case "del":c("#"+b).jqGrid("delGridRow",a,e.delOptions);break}};c.fn.fmatter.actions=function(a,b){a={keys:false,editbutton:true,delbutton:true};c.fmatter.isUndefined(b.colModel.formatoptions)||(a=c.extend(a,b.colModel.formatoptions));var d=b.rowId,f="",e;if(typeof d=="undefined"||c.fmatter.isEmpty(d))return"";if(a.editbutton){e="onclick=$.fn.fmatter.rowactions('"+d+"','"+b.gid+
"','edit',"+b.pos+");";f=f+"<div style='margin-left:8px;'><div title='"+c.jgrid.nav.edittitle+"' style='float:left;cursor:pointer;' class='ui-pg-div ui-inline-edit' "+e+"><span class='ui-icon ui-icon-pencil'></span></div>"}if(a.delbutton){e="onclick=$.fn.fmatter.rowactions('"+d+"','"+b.gid+"','del',"+b.pos+");";f=f+"<div title='"+c.jgrid.nav.deltitle+"' style='float:left;margin-left:5px;' class='ui-pg-div ui-inline-del' "+e+"><span class='ui-icon ui-icon-trash'></span></div>"}e="onclick=$.fn.fmatter.rowactions('"+
d+"','"+b.gid+"','save',"+b.pos+");";f=f+"<div title='"+c.jgrid.edit.bSubmit+"' style='float:left;display:none' class='ui-pg-div ui-inline-save'><span class='ui-icon ui-icon-disk' "+e+"></span></div>";e="onclick=$.fn.fmatter.rowactions('"+d+"','"+b.gid+"','cancel',"+b.pos+");";return f=f+"<div title='"+c.jgrid.edit.bCancel+"' style='float:left;display:none;margin-left:5px;' class='ui-pg-div ui-inline-cancel'><span class='ui-icon ui-icon-cancel' "+e+"></span></div></div>"};c.unformat=function(a,b,
d,f){var e,i=b.colModel.formatter,g=b.colModel.formatoptions||{},h=/([\.\*\_\'\(\)\{\}\+\?\\])/g,j=b.colModel.unformat||c.fn.fmatter[i]&&c.fn.fmatter[i].unformat;if(typeof j!=="undefined"&&c.isFunction(j))e=j(c(a).text(),b,a);else if(!c.fmatter.isUndefined(i)&&c.fmatter.isString(i)){e=c.jgrid.formatter||{};switch(i){case "integer":g=c.extend({},e.integer,g);b=g.thousandsSeparator.replace(h,"\\$1");b=new RegExp(b,"g");e=c(a).text().replace(b,"");break;case "number":g=c.extend({},e.number,g);b=g.thousandsSeparator.replace(h,
"\\$1");b=new RegExp(b,"g");e=c(a).text().replace(b,"").replace(g.decimalSeparator,".");break;case "currency":g=c.extend({},e.currency,g);b=g.thousandsSeparator.replace(h,"\\$1");b=new RegExp(b,"g");e=c(a).text().replace(b,"").replace(g.decimalSeparator,".").replace(g.prefix,"").replace(g.suffix,"");break;case "checkbox":g=b.colModel.editoptions?b.colModel.editoptions.value.split(":"):["Yes","No"];e=c("input",a).attr("checked")?g[0]:g[1];break;case "select":e=c.unformat.select(a,b,d,f);break;case "actions":return"";
default:e=c(a).text()}}return e?e:f===true?c(a).text():c.jgrid.htmlDecode(c(a).html())};c.unformat.select=function(a,b,d,f){d=[];a=c(a).text();if(f===true)return a;b=c.extend({},b.colModel.editoptions);if(b.value){var e=b.value;b=b.multiple===true?true:false;f=[];var i;if(b){f=a.split(",");f=c.map(f,function(k){return c.trim(k)})}if(c.fmatter.isString(e))for(var g=e.split(";"),h=0,j=0;j<g.length;j++){i=g[j].split(":");if(i.length>2)i[1]=jQuery.map(i,function(k,l){if(l>0)return k}).join(":");if(b){if(jQuery.inArray(i[1],
f)>-1){d[h]=i[0];h++}}else if(c.trim(i[1])==c.trim(a)){d[0]=i[0];break}}else if(c.fmatter.isObject(e)||c.isArray(e)){b||(f[0]=a);d=jQuery.map(f,function(k){var l;c.each(e,function(o,n){if(n==k){l=o;return false}});if(typeof l!="undefined")return l})}return d.join(", ")}else return a||""};c.unformat.date=function(a,b){var d=c.jgrid.formatter.date||{};c.fmatter.isUndefined(b.formatoptions)||(d=c.extend({},d,b.formatoptions));return c.fmatter.isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):c.fmatter.util.DateFormat(d.newformat,
a,d.srcformat,d)}})(jQuery);
