(function(a){a.jgrid.extend({getColProp:function(b){var c={},d=this[0];if(!d.grid)return false;d=d.p.colModel;for(var h=0;h<d.length;h++)if(d[h].name==b){c=d[h];break}return c},setColProp:function(b,c){return this.each(function(){if(this.grid)if(c)for(var d=this.p.colModel,h=0;h<d.length;h++)if(d[h].name==b){a.extend(this.p.colModel[h],c);break}})},sortGrid:function(b,c,d){return this.each(function(){var h=this,l=-1;if(h.grid){if(!b)b=h.p.sortname;for(var k=0;k<h.p.colModel.length;k++)if(h.p.colModel[k].index==
b||h.p.colModel[k].name==b){l=k;break}if(l!=-1){k=h.p.colModel[l].sortable;if(typeof k!=="boolean")k=true;if(typeof c!=="boolean")c=false;k&&h.sortData("jqgh_"+h.p.id+"_"+b,l,c,d)}}})},GridDestroy:function(){return this.each(function(){if(this.grid){this.p.pager&&a(this.p.pager).remove();var b=this.id;try{a("#gbox_"+b).remove()}catch(c){}}})},GridUnload:function(){return this.each(function(){if(this.grid){var b={id:a(this).attr("id"),cl:a(this).attr("class")};this.p.pager&&a(this.p.pager).empty().removeClass("ui-state-default ui-jqgrid-pager corner-bottom");
var c=document.createElement("table");a(c).attr({id:b.id});c.className=b.cl;b=this.id;a(c).removeClass("ui-jqgrid-btable");if(a(this.p.pager).parents("#gbox_"+b).length===1){a(c).insertBefore("#gbox_"+b).show();a(this.p.pager).insertBefore("#gbox_"+b)}else a(c).insertBefore("#gbox_"+b).show();a("#gbox_"+b).remove()}})},setGridState:function(b){return this.each(function(){if(this.grid){var c=this;if(b=="hidden"){a(".ui-jqgrid-bdiv, .ui-jqgrid-hdiv","#gview_"+c.p.id).slideUp("fast");c.p.pager&&a(c.p.pager).slideUp("fast");
c.p.toppager&&a(c.p.toppager).slideUp("fast");if(c.p.toolbar[0]===true){c.p.toolbar[1]=="both"&&a(c.grid.ubDiv).slideUp("fast");a(c.grid.uDiv).slideUp("fast")}c.p.footerrow&&a(".ui-jqgrid-sdiv","#gbox_"+c.p.id).slideUp("fast");a(".ui-jqgrid-titlebar-close span",c.grid.cDiv).removeClass("ui-icon-circle-triangle-n").addClass("ui-icon-circle-triangle-s");c.p.gridstate="hidden"}else if(b=="visible"){a(".ui-jqgrid-hdiv, .ui-jqgrid-bdiv","#gview_"+c.p.id).slideDown("fast");c.p.pager&&a(c.p.pager).slideDown("fast");
c.p.toppager&&a(c.p.toppager).slideDown("fast");if(c.p.toolbar[0]===true){c.p.toolbar[1]=="both"&&a(c.grid.ubDiv).slideDown("fast");a(c.grid.uDiv).slideDown("fast")}c.p.footerrow&&a(".ui-jqgrid-sdiv","#gbox_"+c.p.id).slideDown("fast");a(".ui-jqgrid-titlebar-close span",c.grid.cDiv).removeClass("ui-icon-circle-triangle-s").addClass("ui-icon-circle-triangle-n");c.p.gridstate="visible"}}})},filterToolbar:function(b){b=a.extend({autosearch:true,searchOnEnter:true,beforeSearch:null,afterSearch:null,beforeClear:null,
afterClear:null,searchurl:"",stringResult:false,groupOp:"AND",defaultSearch:"bw"},b||{});return this.each(function(){function c(e,g){var i=a(e);i[0]&&jQuery.each(g,function(){this.data!==undefined?i.bind(this.type,this.data,this.fn):i.bind(this.type,this.fn)})}var d=this;if(!this.ftoolbar){var h=function(){var e={},g=0,i,f,j={},n;a.each(d.p.colModel,function(){f=this.index||this.name;n=this.searchoptions&&this.searchoptions.sopt?this.searchoptions.sopt[0]:this.stype=="select"?"eq":b.defaultSearch;
if(i=a("#gs_"+a.jgrid.jqID(this.name),this.frozen===true&&d.p.frozenColumns===true?d.grid.fhDiv:d.grid.hDiv).val()){e[f]=i;j[f]=n;g++}else try{delete d.p.postData[f]}catch(r){}});var o=g>0?true:false;if(b.stringResult===true||d.p.datatype=="local"){var m='{"groupOp":"'+b.groupOp+'","rules":[',t=0;a.each(e,function(r,v){if(t>0)m+=",";m+='{"field":"'+r+'",';m+='"op":"'+j[r]+'",';v+="";m+='"data":"'+v.replace(/\\/g,"\\\\").replace(/\"/g,'\\"')+'"}';t++});m+="]}";a.extend(d.p.postData,{filters:m});a.each(["searchField",
"searchString","searchOper"],function(r,v){d.p.postData.hasOwnProperty(v)&&delete d.p.postData[v]})}else a.extend(d.p.postData,e);var p;if(d.p.searchurl){p=d.p.url;a(d).jqGrid("setGridParam",{url:d.p.searchurl})}var q=false;if(a.isFunction(b.beforeSearch))q=b.beforeSearch.call(d);q||a(d).jqGrid("setGridParam",{search:o}).trigger("reloadGrid",[{page:1}]);p&&a(d).jqGrid("setGridParam",{url:p});a.isFunction(b.afterSearch)&&b.afterSearch()},l=a("<tr class='ui-search-toolbar' role='rowheader'></tr>"),
k;a.each(d.p.colModel,function(){var e=this,g,i,f,j;i=a("<th role='columnheader' class='ui-state-default ui-th-column ui-th-"+d.p.direction+"'></th>");g=a("<div style='width:100%;position:relative;height:100%;padding-right:0.3em;'></div>");this.hidden===true&&a(i).css("display","none");this.search=this.search===false?false:true;if(typeof this.stype=="undefined")this.stype="text";f=a.extend({},this.searchoptions||{});if(this.search)switch(this.stype){case "select":if(j=this.surl||f.dataUrl)a.ajax(a.extend({url:j,
dataType:"html",success:function(p){if(f.buildSelect!==undefined)(p=f.buildSelect(p))&&a(g).append(p);else a(g).append(p);f.defaultValue&&a("select",g).val(f.defaultValue);a("select",g).attr({name:e.index||e.name,id:"gs_"+e.name});f.attr&&a("select",g).attr(f.attr);a("select",g).css({width:"100%"});f.dataInit!==undefined&&f.dataInit(a("select",g)[0]);f.dataEvents!==undefined&&c(a("select",g)[0],f.dataEvents);b.autosearch===true&&a("select",g).change(function(){h();return false});p=null}},a.jgrid.ajaxOptions,
d.p.ajaxSelectOptions||{}));else{var n;if(e.searchoptions&&e.searchoptions.value)n=e.searchoptions.value;else if(e.editoptions&&e.editoptions.value)n=e.editoptions.value;if(n){j=document.createElement("select");j.style.width="100%";a(j).attr({name:e.index||e.name,id:"gs_"+e.name});var o,m;if(typeof n==="string"){n=n.split(";");for(var t=0;t<n.length;t++){o=n[t].split(":");m=document.createElement("option");m.value=o[0];m.innerHTML=o[1];j.appendChild(m)}}else if(typeof n==="object")for(o in n)if(n.hasOwnProperty(o)){m=
document.createElement("option");m.value=o;m.innerHTML=n[o];j.appendChild(m)}f.defaultValue&&a(j).val(f.defaultValue);f.attr&&a(j).attr(f.attr);f.dataInit!==undefined&&f.dataInit(j);f.dataEvents!==undefined&&c(j,f.dataEvents);a(g).append(j);b.autosearch===true&&a(j).change(function(){h();return false})}}break;case "text":j=f.defaultValue?f.defaultValue:"";a(g).append("<input type='text' style='width:95%;padding:0px;' name='"+(e.index||e.name)+"' id='gs_"+e.name+"' value='"+j+"'/>");f.attr&&a("input",
g).attr(f.attr);f.dataInit!==undefined&&f.dataInit(a("input",g)[0]);f.dataEvents!==undefined&&c(a("input",g)[0],f.dataEvents);if(b.autosearch===true)b.searchOnEnter?a("input",g).keypress(function(p){if((p.charCode?p.charCode:p.keyCode?p.keyCode:0)==13){h();return false}return this}):a("input",g).keydown(function(p){switch(p.which){case 13:return false;case 9:case 16:case 37:case 38:case 39:case 40:case 27:break;default:k&&clearTimeout(k);k=setTimeout(function(){h()},500)}});break}a(i).append(g);a(l).append(i)});
a("table thead",d.grid.hDiv).append(l);this.ftoolbar=true;this.triggerToolbar=h;this.clearToolbar=function(e){var g={},i,f=0,j;e=typeof e!="boolean"?true:e;a.each(d.p.colModel,function(){i=this.searchoptions&&this.searchoptions.defaultValue?this.searchoptions.defaultValue:"";j=this.index||this.name;switch(this.stype){case "select":var q;a("#gs_"+a.jgrid.jqID(this.name)+" option",this.frozen===true&&d.p.frozenColumns===true?d.grid.fhDiv:d.grid.hDiv).each(function(s){if(s===0)this.selected=true;if(a(this).text()==
i){this.selected=true;q=a(this).val();return false}});if(q){g[j]=q;f++}else try{delete d.p.postData[j]}catch(r){}break;case "text":a("#gs_"+a.jgrid.jqID(this.name),this.frozen===true&&d.p.frozenColumns===true?d.grid.fhDiv:d.grid.hDiv).val(i);if(i){g[j]=i;f++}else try{delete d.p.postData[j]}catch(v){}break}});var n=f>0?true:false;if(b.stringResult===true||d.p.datatype=="local"){var o='{"groupOp":"'+b.groupOp+'","rules":[',m=0;a.each(g,function(q,r){if(m>0)o+=",";o+='{"field":"'+q+'",';o+='"op":"eq",';
r+="";o+='"data":"'+r.replace(/\\/g,"\\\\").replace(/\"/g,'\\"')+'"}';m++});o+="]}";a.extend(d.p.postData,{filters:o});a.each(["searchField","searchString","searchOper"],function(q,r){d.p.postData.hasOwnProperty(r)&&delete d.p.postData[r]})}else a.extend(d.p.postData,g);var t;if(d.p.searchurl){t=d.p.url;a(d).jqGrid("setGridParam",{url:d.p.searchurl})}var p=false;if(a.isFunction(b.beforeClear))p=b.beforeClear.call(d);p||e&&a(d).jqGrid("setGridParam",{search:n}).trigger("reloadGrid",[{page:1}]);t&&
a(d).jqGrid("setGridParam",{url:t});a.isFunction(b.afterClear)&&b.afterClear()};this.toggleToolbar=function(){var e=a("tr.ui-search-toolbar",d.grid.hDiv),g=d.p.frozenColumns===true?a("tr.ui-search-toolbar",d.grid.hDiv):false;if(e.css("display")=="none"){e.show();g&&g.show()}else{e.hide();g&&g.hide()}}}})},destroyGroupHeader:function(b){if(typeof b=="undefined")b=true;return this.each(function(){var c=this,d,h,l,k,e,g;h=c.grid;var i=a("table.ui-jqgrid-htable thead",h.hDiv),f=c.p.colModel;if(h){d=a("<tr>",
{role:"rowheader"}).addClass("ui-jqgrid-labels");k=h.headers;h=0;for(l=k.length;h<l;h++){e=f[h].hidden?"none":"";e=a(k[h].el).width(k[h].width).css("display",e);try{e.removeAttr("rowSpan")}catch(j){e.attr("rowSpan",1)}d.append(e);g=e.children("span.ui-jqgrid-resize");if(g.length>0)g[0].style.height="";e.children("div")[0].style.top=""}a(i).children("tr.ui-jqgrid-labels").remove();a(i).prepend(d);b===true&&a(c).jqGrid("setGridParam",{groupHeader:null})}})},setGroupHeaders:function(b){b=a.extend({useColSpanStyle:false,
groupHeaders:[]},b||{});return this.each(function(){this.p.groupHeader=b;var c=this,d,h,l=0,k,e,g,i,f,j=c.p.colModel,n=j.length,o=c.grid.headers,m=a("table.ui-jqgrid-htable",c.grid.hDiv),t=m.children("thead").children("tr.ui-jqgrid-labels:last").addClass("jqg-second-row-header");k=m.children("thead");var p,q=m.find(".jqg-first-row-header");if(q.html()===null)q=a("<tr>",{role:"row","aria-hidden":"true"}).addClass("jqg-first-row-header").css("height","auto");else q.empty();var r,v=function(s,u){for(var w=
0,x=u.length;w<x;w++)if(u[w].startColumnName===s)return w;return-1};a(c).prepend(k);k=a("<tr>",{role:"rowheader"}).addClass("ui-jqgrid-labels jqg-third-row-header");for(d=0;d<n;d++){g=o[d].el;i=a(g);h=j[d];e={height:"0px",width:o[d].width+"px",display:h.hidden?"none":""};a("<th>",{role:"gridcell"}).css(e).addClass("ui-first-th-"+c.p.direction).appendTo(q);g.style.width="";e=v(h.name,b.groupHeaders);if(e>=0){e=b.groupHeaders[e];l=e.numberOfColumns;f=e.titleText;for(e=h=0;e<l&&d+e<n;e++)j[d+e].hidden||
h++;e=a("<th>").attr({role:"columnheader"}).addClass("ui-state-default ui-th-column-header ui-th-"+c.p.direction).css({height:"22px","border-top":"0px none"}).html(f);h>0&&e.attr("colspan",String(h));c.p.headertitles&&e.attr("title",e.text());h===0&&e.hide();i.before(e);k.append(g);l=l-1}else if(l===0)if(b.useColSpanStyle)i.attr("rowspan","2");else{a("<th>",{role:"columnheader"}).addClass("ui-state-default ui-th-column-header ui-th-"+c.p.direction).css({display:h.hidden?"none":"","border-top":"0px none"}).insertBefore(i);
k.append(g)}else{k.append(g);l--}}j=a(c).children("thead");j.prepend(q);k.insertAfter(t);m.append(j);if(b.useColSpanStyle){m.find("span.ui-jqgrid-resize").each(function(){var s=a(this).parent();if(s.is(":visible"))this.style.cssText="height: "+s.height()+"px !important; cursor: col-resize;"});m.find("div.ui-jqgrid-sortable").each(function(){var s=a(this),u=s.parent();u.is(":visible")&&u.is(":has(span.ui-jqgrid-resize)")&&s.css("top",(u.height()-s.outerHeight())/2+"px")})}if(a.isFunction(c.p.resizeStop))p=
c.p.resizeStop;r=j.find("tr.jqg-first-row-header");c.p.resizeStop=function(s,u){r.find("th").eq(u).width(s);a.isFunction(p)&&p.call(c,s,u)}})},setFrozenColumns:function(){return this.each(function(){if(this.grid){var b=this,c=b.p.colModel,d=0,h=c.length,l=-1,k=false;if(!(b.p.subGrid==true||b.p.treeGrid===true||b.p.cellEdit==true||b.p.sortable||b.p.scroll||b.p.grouping)){b.p.rownumbers&&d++;for(b.p.multiselect&&d++;d<h;){if(c[d].frozen===true){k=true;l=d}else break;d++}if(l>=0&&k){c=b.p.caption?a(b.grid.cDiv).outerHeight():
0;d=a(".ui-jqgrid-htable","#gview_"+a.jgrid.jqID(b.p.id)).height();b.p.orgEvents={};if(b.p.toppager)c+=a(b.grid.topDiv).outerHeight();if(b.p.toolbar[0]==true)if(b.p.toolbar[1]!="bottom")c+=a(b.grid.uDiv).outerHeight();b.grid.fhDiv=a('<div style="position:absolute;left:0px;top:'+c+"px;height:"+d+'px;" class="frozen-div ui-state-default ui-jqgrid-hdiv"></div>');b.grid.fbDiv=a('<div style="position:absolute;left:0px;top:'+(parseInt(c,10)+parseInt(d,10)+1)+'px;overflow-y:hidden" class="frozen-bdiv ui-jqgrid-bdiv"></div>');
a("#gview_"+a.jgrid.jqID(b.p.id)).append(b.grid.fhDiv);c=a(".ui-jqgrid-htable","#gview_"+a.jgrid.jqID(b.p.id)).clone(true);if(b.p.groupHeader){a("tr.jqg-first-row-header, tr.jqg-third-row-header",c).each(function(){a("th:gt("+l+")",this).remove()});var e=-1,g=-1;a("tr.jqg-second-row-header th",c).each(function(){var i=parseInt(a(this).attr("colspan"),10);if(i){e+=i;g++}if(e===l)return false});if(e!==l)g=l;a("tr.jqg-second-row-header",c).each(function(){a("th:gt("+g+")",this).remove()})}else a("tr",
c).each(function(){a("th:gt("+l+")",this).remove()});a(c).width(1);a(b.grid.fhDiv).append(c).mousemove(function(i){if(b.grid.resizing){b.grid.dragMove(i);return false}});if(a.isFunction(b.p.resizeStop))b.p.orgEvents.resizeStop=b.p.resizeStop;b.p.resizeStop=function(i,f){var j=a(".ui-jqgrid-htable",b.grid.fhDiv);a("th:eq("+f+")",j).width(i);j=a(".ui-jqgrid-btable",b.grid.fbDiv);a("tr:first td:eq("+f+")",j).width(i);if(a.isFunction(b.p.orgEvents.resizeStop))b.p.orgEvents.resizeStop.call(b,i,f);else b.p.orgEvents.resizeStop=
null};b.p.orgEvents.onSortCol=a.isFunction(b.p.onSortCol)?b.p.onSortCol:null;b.p.onSortCol=function(i,f,j){var n=a("tr.ui-jqgrid-labels:last th:eq("+b.p.lastsort+")",b.grid.fhDiv),o=a("tr.ui-jqgrid-labels:last th:eq("+f+")",b.grid.fhDiv);a("span.ui-grid-ico-sort",n).addClass("ui-state-disabled");a(n).attr("aria-selected","false");a("span.ui-icon-"+b.p.sortorder,o).removeClass("ui-state-disabled");a(o).attr("aria-selected","true");if(!b.p.viewsortcols[0])if(b.p.lastsort!=f){a("span.s-ico",n).hide();
a("span.s-ico",o).show()}a.isFunction(b.p.orgEvents.onSortCol)&&b.p.orgEvents.onSortCol.call(b,i,f,j)};a("#gview_"+a.jgrid.jqID(b.p.id)).append(b.grid.fbDiv);jQuery(b.grid.bDiv).scroll(function(){jQuery(b.grid.fbDiv).scrollTop(jQuery(this).scrollTop())});b.p.orgEvents.complete=a.isFunction(b.p._complete)?b.p._complete:null;b.p.hoverrows===true&&a("#"+a.jgrid.jqID(b.p.id)).unbind("mouseover").unbind("mouseout");b.p._complete=function(){a("#"+a.jgrid.jqID(b.p.id)+"_frozen").remove();jQuery(b.grid.fbDiv).height(jQuery(b.grid.bDiv).height()-
16);var i=a("#"+a.jgrid.jqID(b.p.id)).clone(true);a("tr",i).each(function(){a("td:gt("+l+")",this).remove()});a(i).width(1).attr("id",a.jgrid.jqID(b.p.id)+"_frozen");a(b.grid.fbDiv).append(i);if(b.p.hoverrows===true){a("tr.jqgrow",i).hover(function(){a(this).addClass("ui-state-hover");a("#"+a.jgrid.jqID(this.id),"#"+a.jgrid.jqID(b.p.id)).addClass("ui-state-hover")},function(){a(this).removeClass("ui-state-hover");a("#"+a.jgrid.jqID(this.id),"#"+a.jgrid.jqID(b.p.id)).removeClass("ui-state-hover")});
a("tr.jqgrow","#"+a.jgrid.jqID(b.p.id)).hover(function(){a(this).addClass("ui-state-hover");a("#"+a.jgrid.jqID(this.id),"#"+a.jgrid.jqID(b.p.id)+"_frozen").addClass("ui-state-hover")},function(){a(this).removeClass("ui-state-hover");a("#"+a.jgrid.jqID(this.id),"#"+a.jgrid.jqID(b.p.id)+"_frozen").removeClass("ui-state-hover")})}i=null;a.isFunction(b.p.orgEvents.complete)&&b.p.orgEvents.complete.call(b)};b.p.frozenColumns=true}}}})},destroyFrozenColumns:function(){return this.each(function(){if(this.grid)if(this.p.frozenColumns===
true){var b=this;a(b.grid.fhDiv).remove();a(b.grid.fbDiv).remove();b.grid.fhDiv=null;b.grid.fbDiv=null;b.p._complete=b.p.orgEvents.complete;b.p.resizeStop=b.p.orgEvents.resizeStop;b.p.onSortCol=b.p.orgEvents.onSortCol;b.p.orgEvents=null;if(b.p.hoverrows==true){var c;a("#"+a.jgrid.jqID(b.p.id)).bind("mouseover",function(d){c=a(d.target).closest("tr.jqgrow");a(c).attr("class")!=="ui-subgrid"&&a(c).addClass("ui-state-hover")}).bind("mouseout",function(d){c=a(d.target).closest("tr.jqgrow");a(c).removeClass("ui-state-hover")})}this.p.frozenColumns=
false}})}})})(jQuery);
